### ISSUE TITLE
how to adapt it to work with multiple arguments?

### ISSUE THREAD

**Issue by NinoFoxx** [iridakos-tutorials/bash-completion-tutorial#8]
I'm creating a script that's supposed to manage a few files in the system. list them, create them, delete them.

I followed your bash completion guide but it does not mention working with arguments.

example: one of the commands of my script would be `script remove <name>`. name would be a file in a directory.

but other arguments would use the same completion, like `script disable <name>` and `script enable <name>`

how could I make it so that it works with multiple arguments?

thank you.

**Comment by vaclavblazej** [comment]
@NinoM4ster You can perform completion of the command name if `"${#COMP_WORDS[@]}" == "2"` and perform completion of its argument if `"${#COMP_WORDS[@]}" == "3"`. Also, you should confirm that the command given was one of the three you mentioned (`remove`, `disable`, or `enable`) when you are checking for the argument.

If you want more general (command dependent) completion, then you can use `shift` to gobble the first argument, and defer the completion to respective command, i.e., you would create separate function to handle completion for `remove`, `disable`, etc.

**Comment by vaclavblazej** [comment]
@NinoM4ster Also a similar issue to your was solved here `https://github.com/iridakos/goto/blob/master/goto.sh` by the author of this tutorial.

**Comment by NinoFoxx** [comment]
I'm sorry, I completely forgot to close this.

Thanks @vaclavblazej for the useful informations.  :)
